### ISSUE TITLE
サイトにメールアドレス登録欄を入れる

### ISSUE THREAD

**Issue by sentogurashi1126** [sentogurashi/ec#1]
# これは何
- トップページの下のほうと各商品ページの下にメールチンプの顧客リストに入るembed formを作りたい
![image (4)](https://user-images.githubusercontent.com/65495352/82313029-c42b3700-9a02-11ea-8848-4c7942f3718c.png)

# なぜ
## 前提
- 本日5/19と翌日5/20、5/17日に発注した第一陣発送の32件分がお客様のもとに届き、「#銭湯のあるくらし便」ないし「#おうちで銭湯」で投稿する方が一定数いると思われます(ぼくの同僚やハナウタカジツの片山さんは確実。インフルエンサーの暁子さんも初回発送に含まれているので今日か明日には届きます)　
- そして、その方々経由でまたバズってしまう可能性もあり得ます。
- また、今週末で現場スタッフもふくめて配送祭りをやったら、うまくいけば現時点での全ての注文が日曜日に発送でき、5/26か5/27には300人以上のもとにくらし便が届きます。

## 対応
- 今日～週明けで届いた方々の声経由でサイトを知り、商品を欲しいと思った方々がサイトにきたらほとんどの商品が売切れでガッカリさせてしまうのはよくないなと思う
- 折衷案として「トップページの商品一覧の下と各商品の説明の下にメール登録フォームを用意し、発送できる体制ができたら(できればnoteの記事などともいっしょに)連絡する」というふうにし、第一陣の機会損失をなくす

# 埋め込みコード
```
<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://sentogurashi.us18.list-manage.com/subscribe/post?u=e80778fca6e1d4bc40f69bccb&amp;id=7bf9fb5a41" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">お知らせを受け取る</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_e80778fca6e1d4bc40f69bccb_7bf9fb5a41" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<!--End mc_embed_signup-->
```

# 参考
- mailchimpのsign up form のヘルプ　https://mailchimp.com/help/add-a-signup-form-to-your-website/

**Comment by sentogurashi1126** [comment]
@ogwtkhr 頼むっ

**Comment by ogwtkhr** [comment]
@sentogurashi1126 
対応したヨン
https://github.com/sentogurashi/ec/commit/e40674f44b1872b7e8d10a45630fc5f94bc97419
