### ISSUE TITLE
Shopifyに移管したい

### ISSUE THREAD

**Issue by sentogurashi1126** [sentogurashi/ec#2]
# これは何
- 売上の目標値を考えるとPFをbaseからshopifyに移行したほうがいいかも
- すぐすぐは無理なので、半年後(2020.10月)とかを見据えて予算を検討
- FBもコマース始めたりしてたので他PFも含めて検討する

# なぜ
- baseは手数料が高い
- 機能の不足。メールチンプとかと連携してないのが微妙

## 値段の比較
- baseはなんだかんだ決済手数料6.6% + 40円かかってる
![image (5)](https://user-images.githubusercontent.com/65495352/82619736-b992bc80-9c11-11ea-956a-65690dd9bd11.png)
- shopifyは固定3,000円 + 決済手数料3.5%とかでいける

# todo
- baseとshopifyどっちがお得かや機能比較する | naoki

# 参考
- [Shopifyへの移行](https://help.shopify.com/ja/manual/migrating-to-shopify)
- [tag manager](https://help.shopify.com/en/manual/reports-and-analytics/google-analytics/google-tag-manager)

**Comment by ogwtkhr** [comment]
Shipifyのほうがイケテル感も++
なので、やってきましょう！
